#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set .aj.animation aj.crab_trap.animating 0
scoreboard players set .aj.anim_loop aj.crab_trap.animating 0
scoreboard players set .noScripts aj.i 0