#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 107 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 108 run data modify entity @s Pose.Head set value [0f,1.5f,0f]
execute if score .this aj.frame matches 109 run data modify entity @s Pose.Head set value [0f,4.5f,0f]
execute if score .this aj.frame matches 110 run data modify entity @s Pose.Head set value [0f,7.5f,0f]
execute if score .this aj.frame matches 111 run data modify entity @s Pose.Head set value [0f,10.5f,0f]