#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^0.327 ^-1.311 ^0.075 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^0.327 ^-1.311 ^0.075 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^0.327 ^-1.311 ^0.075 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^0.327 ^-1.311 ^0.075 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^0.327 ^-1.311 ^0.075 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^0.327 ^-1.327 ^0.059 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^0.327 ^-1.328 ^0.058 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^0.327 ^-1.332 ^0.054 ~ ~