#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 248 run tp @s ^-0.107 ^-1.717 ^0.103 ~ ~
execute if score .this aj.frame matches 249 run tp @s ^-0.107 ^-1.717 ^0.104 ~ ~
execute if score .this aj.frame matches 250 run tp @s ^-0.107 ^-1.717 ^0.104 ~ ~
execute if score .this aj.frame matches 251 run tp @s ^-0.107 ^-1.717 ^0.104 ~ ~
execute if score .this aj.frame matches 252 run tp @s ^-0.107 ^-1.717 ^0.104 ~ ~
execute if score .this aj.frame matches 253 run tp @s ^-0.099 ^-1.717 ^0.112 ~ ~
execute if score .this aj.frame matches 254 run tp @s ^-0.096 ^-1.717 ^0.115 ~ ~
execute if score .this aj.frame matches 255 run tp @s ^-0.093 ^-1.717 ^0.118 ~ ~