#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run data modify entity @s Pose.Head set value [0f,11.9444f,0f]
execute if score .this aj.frame matches 113 run data modify entity @s Pose.Head set value [0f,10.2778f,0f]
execute if score .this aj.frame matches 114 run data modify entity @s Pose.Head set value [0f,8.6111f,0f]
execute if score .this aj.frame matches 115 run data modify entity @s Pose.Head set value [0f,6.9444f,0f]
execute if score .this aj.frame matches 116 run data modify entity @s Pose.Head set value [0f,5.2778f,0f]
execute if score .this aj.frame matches 117 run data modify entity @s Pose.Head set value [0f,3.6111f,0f]
execute if score .this aj.frame matches 118 run data modify entity @s Pose.Head set value [0f,1.9444f,0f]
execute if score .this aj.frame matches 119 run data modify entity @s Pose.Head set value [0f,0.2778f,0f]