#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^0.327 ^-1.285 ^0.101 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^0.327 ^-1.289 ^0.097 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^0.327 ^-1.293 ^0.093 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^0.327 ^-1.297 ^0.089 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^0.327 ^-1.3 ^0.086 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^0.327 ^-1.301 ^0.085 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^0.327 ^-1.303 ^0.082 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^0.327 ^-1.31 ^0.076 ~ ~