#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 176 run tp @s ^0.168 ^-1.719 ^-0.081 ~ ~
execute if score .this aj.frame matches 177 run tp @s ^0.168 ^-1.719 ^-0.081 ~ ~
execute if score .this aj.frame matches 178 run tp @s ^0.168 ^-1.719 ^-0.081 ~ ~
execute if score .this aj.frame matches 179 run tp @s ^0.168 ^-1.719 ^-0.081 ~ ~
execute if score .this aj.frame matches 180 run tp @s ^0.168 ^-1.719 ^-0.081 ~ ~
execute if score .this aj.frame matches 181 run tp @s ^0.168 ^-1.719 ^-0.081 ~ ~
execute if score .this aj.frame matches 182 run tp @s ^0.168 ^-1.719 ^-0.081 ~ ~
execute if score .this aj.frame matches 183 run tp @s ^0.168 ^-1.719 ^-0.081 ~ ~