#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 208..215 run function crab_trap:animations/crab.move/tree/crab_export5_display_208-215
execute if score .this aj.frame matches 239 run data modify entity @s Pose.Head set value [0f,-15f,0f]
execute if score .this aj.frame matches 240 run data modify entity @s Pose.Head set value [-180f,15f,180f]