#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [-180f,15f,180f]
execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 112..119 run function crab_trap:animations/crab.move/tree/crab_export5_display_112-119