#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^-0.307 ^-1.251 ^-0.094 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^-0.307 ^-1.249 ^-0.096 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^-0.307 ^-1.247 ^-0.099 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^-0.307 ^-1.244 ^-0.101 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^-0.307 ^-1.242 ^-0.103 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^-0.307 ^-1.24 ^-0.105 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^-0.307 ^-1.238 ^-0.108 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^-0.307 ^-1.235 ^-0.11 ~ ~