#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 192 run tp @s ^0.327 ^-1.436 ^-0.05 ~ ~
execute if score .this aj.frame matches 193 run tp @s ^0.327 ^-1.436 ^-0.05 ~ ~
execute if score .this aj.frame matches 194 run tp @s ^0.327 ^-1.436 ^-0.05 ~ ~
execute if score .this aj.frame matches 195 run tp @s ^0.327 ^-1.422 ^-0.036 ~ ~
execute if score .this aj.frame matches 196 run tp @s ^0.327 ^-1.419 ^-0.033 ~ ~
execute if score .this aj.frame matches 197 run tp @s ^0.327 ^-1.414 ^-0.028 ~ ~
execute if score .this aj.frame matches 198 run tp @s ^0.327 ^-1.41 ^-0.024 ~ ~
execute if score .this aj.frame matches 199 run tp @s ^0.327 ^-1.406 ^-0.02 ~ ~