#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0.327 ^-1.28 ^0.106 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0.327 ^-1.28 ^0.106 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0.327 ^-1.28 ^0.106 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0.327 ^-1.28 ^0.106 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^0.327 ^-1.28 ^0.106 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^0.327 ^-1.28 ^0.106 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^0.327 ^-1.28 ^0.106 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^0.327 ^-1.281 ^0.105 ~ ~