#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 192 run tp @s ^-0.107 ^-1.717 ^0.104 ~ ~
execute if score .this aj.frame matches 193 run tp @s ^-0.099 ^-1.717 ^0.112 ~ ~
execute if score .this aj.frame matches 194 run tp @s ^-0.097 ^-1.717 ^0.114 ~ ~
execute if score .this aj.frame matches 195 run tp @s ^-0.095 ^-1.717 ^0.116 ~ ~
execute if score .this aj.frame matches 196 run tp @s ^-0.093 ^-1.717 ^0.117 ~ ~
execute if score .this aj.frame matches 197 run tp @s ^-0.092 ^-1.717 ^0.119 ~ ~
execute if score .this aj.frame matches 198 run tp @s ^-0.09 ^-1.717 ^0.12 ~ ~
execute if score .this aj.frame matches 199 run tp @s ^-0.089 ^-1.717 ^0.121 ~ ~