#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 232 run tp @s ^-0.307 ^-1.439 ^0.094 ~ ~
execute if score .this aj.frame matches 233 run tp @s ^-0.307 ^-1.443 ^0.098 ~ ~
execute if score .this aj.frame matches 234 run tp @s ^-0.307 ^-1.443 ^0.098 ~ ~
execute if score .this aj.frame matches 235 run tp @s ^-0.307 ^-1.443 ^0.098 ~ ~
execute if score .this aj.frame matches 236 run tp @s ^-0.307 ^-1.443 ^0.098 ~ ~
execute if score .this aj.frame matches 237 run tp @s ^-0.307 ^-1.443 ^0.098 ~ ~
execute if score .this aj.frame matches 238 run tp @s ^-0.307 ^-1.467 ^0.121 ~ ~
execute if score .this aj.frame matches 239 run tp @s ^-0.307 ^-1.458 ^0.112 ~ ~