#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 144..151 run function crab_trap:animations/crab.move/tree/crab_export5_display_144-151
execute if score .this aj.frame matches 176..183 run function crab_trap:animations/crab.move/tree/crab_export5_display_176-183