#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 120..127 run function crab_trap:animations/crab.move/tree/crab_export4_display_120-127
execute if score .this aj.frame matches 279 run data modify entity @s Pose.Head set value [92.5f,0f,-180f]