#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 256 run tp @s ^-0.09 ^-1.717 ^0.12 ~ ~
execute if score .this aj.frame matches 257 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 258 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 259 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 260 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 261 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 262 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 263 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~