#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^-0.307 ^-1.342 ^-0.003 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.307 ^-1.342 ^-0.003 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.307 ^-1.33 ^-0.015 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.307 ^-1.329 ^-0.017 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.307 ^-1.327 ^-0.019 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.307 ^-1.325 ^-0.021 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.307 ^-1.322 ^-0.023 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.307 ^-1.32 ^-0.025 ~ ~