#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [0f,-15f,0f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [0f,-15f,0f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [0f,-14.25f,0f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [0f,-9.75f,0f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [0f,-5.25f,0f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [0f,-0.75f,0f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [0f,0f,0f]