#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^-0.097 ^-1.717 ^0.114 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.095 ^-1.717 ^0.116 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.093 ^-1.717 ^0.117 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.092 ^-1.717 ^0.119 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.09 ^-1.717 ^0.12 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.089 ^-1.717 ^0.121 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~