#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 168 run data modify entity @s Pose.Head set value [0f,11.5f,0f]
execute if score .this aj.frame matches 169 run data modify entity @s Pose.Head set value [0f,11.3889f,0f]
execute if score .this aj.frame matches 170 run data modify entity @s Pose.Head set value [0f,9.7222f,0f]
execute if score .this aj.frame matches 171 run data modify entity @s Pose.Head set value [0f,8.0556f,0f]
execute if score .this aj.frame matches 172 run data modify entity @s Pose.Head set value [0f,6.3889f,0f]
execute if score .this aj.frame matches 173 run data modify entity @s Pose.Head set value [0f,4.7222f,0f]
execute if score .this aj.frame matches 174 run data modify entity @s Pose.Head set value [0f,3.0556f,0f]
execute if score .this aj.frame matches 175 run data modify entity @s Pose.Head set value [0f,1.3889f,0f]