#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 152 run tp @s ^-0.307 ^-1.299 ^-0.046 ~ ~
execute if score .this aj.frame matches 153 run tp @s ^-0.307 ^-1.302 ^-0.044 ~ ~
execute if score .this aj.frame matches 154 run tp @s ^-0.307 ^-1.304 ^-0.041 ~ ~
execute if score .this aj.frame matches 155 run tp @s ^-0.307 ^-1.306 ^-0.039 ~ ~
execute if score .this aj.frame matches 156 run tp @s ^-0.307 ^-1.309 ^-0.036 ~ ~
execute if score .this aj.frame matches 157 run tp @s ^-0.307 ^-1.311 ^-0.034 ~ ~
execute if score .this aj.frame matches 158 run tp @s ^-0.307 ^-1.314 ^-0.032 ~ ~
execute if score .this aj.frame matches 159 run tp @s ^-0.307 ^-1.316 ^-0.029 ~ ~