#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.327 ^-1.217 ^0.168 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.327 ^-1.219 ^0.167 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.327 ^-1.223 ^0.163 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.327 ^-1.227 ^0.158 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.327 ^-1.232 ^0.153 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.327 ^-1.237 ^0.149 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.327 ^-1.24 ^0.146 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.327 ^-1.241 ^0.145 ~ ~