#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 160 run tp @s ^-0.117 ^-1.717 ^0.093 ~ ~
execute if score .this aj.frame matches 161 run tp @s ^-0.118 ^-1.717 ^0.092 ~ ~
execute if score .this aj.frame matches 162 run tp @s ^-0.121 ^-1.717 ^0.089 ~ ~
execute if score .this aj.frame matches 163 run tp @s ^-0.128 ^-1.717 ^0.082 ~ ~
execute if score .this aj.frame matches 164 run tp @s ^-0.128 ^-1.717 ^0.082 ~ ~
execute if score .this aj.frame matches 165 run tp @s ^-0.128 ^-1.717 ^0.082 ~ ~
execute if score .this aj.frame matches 166 run tp @s ^-0.128 ^-1.717 ^0.082 ~ ~
execute if score .this aj.frame matches 167 run tp @s ^-0.128 ^-1.717 ^0.082 ~ ~