#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 124 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 125 run data modify entity @s Pose.Head set value [92.5f,0f,-180f]