#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 216 run tp @s ^0.327 ^-1.357 ^0.029 ~ ~
execute if score .this aj.frame matches 217 run tp @s ^0.327 ^-1.353 ^0.033 ~ ~
execute if score .this aj.frame matches 218 run tp @s ^0.327 ^-1.348 ^0.038 ~ ~
execute if score .this aj.frame matches 219 run tp @s ^0.327 ^-1.344 ^0.042 ~ ~
execute if score .this aj.frame matches 220 run tp @s ^0.327 ^-1.342 ^0.043 ~ ~
execute if score .this aj.frame matches 221 run tp @s ^0.327 ^-1.341 ^0.045 ~ ~
execute if score .this aj.frame matches 222 run tp @s ^0.327 ^-1.338 ^0.048 ~ ~
execute if score .this aj.frame matches 223 run tp @s ^0.327 ^-1.334 ^0.052 ~ ~