#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 200 run tp @s ^-0.307 ^-1.404 ^0.059 ~ ~
execute if score .this aj.frame matches 201 run tp @s ^-0.307 ^-1.404 ^0.059 ~ ~
execute if score .this aj.frame matches 202 run tp @s ^-0.307 ^-1.404 ^0.059 ~ ~
execute if score .this aj.frame matches 203 run tp @s ^-0.307 ^-1.404 ^0.059 ~ ~
execute if score .this aj.frame matches 204 run tp @s ^-0.307 ^-1.404 ^0.059 ~ ~
execute if score .this aj.frame matches 205 run tp @s ^-0.307 ^-1.404 ^0.059 ~ ~
execute if score .this aj.frame matches 206 run tp @s ^-0.307 ^-1.413 ^0.067 ~ ~
execute if score .this aj.frame matches 207 run tp @s ^-0.307 ^-1.413 ^0.068 ~ ~