#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run tp @s ^-0.115 ^-1.717 ^0.095 ~ ~
execute if score .this aj.frame matches 121 run tp @s ^-0.113 ^-1.717 ^0.098 ~ ~
execute if score .this aj.frame matches 122 run tp @s ^-0.112 ^-1.717 ^0.099 ~ ~
execute if score .this aj.frame matches 123 run tp @s ^-0.111 ^-1.717 ^0.1 ~ ~
execute if score .this aj.frame matches 124 run tp @s ^-0.108 ^-1.717 ^0.102 ~ ~
execute if score .this aj.frame matches 125 run tp @s ^-0.107 ^-1.717 ^0.104 ~ ~
execute if score .this aj.frame matches 126 run tp @s ^-0.107 ^-1.717 ^0.104 ~ ~
execute if score .this aj.frame matches 127 run tp @s ^-0.107 ^-1.717 ^0.104 ~ ~