#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^-0.116 ^-1.717 ^0.095 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^-0.117 ^-1.717 ^0.093 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^-0.118 ^-1.717 ^0.092 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^-0.126 ^-1.717 ^0.084 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^-0.128 ^-1.717 ^0.082 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^-0.128 ^-1.717 ^0.082 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^-0.128 ^-1.717 ^0.082 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^-0.128 ^-1.717 ^0.082 ~ ~