#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.307 ^-1.35 ^0.005 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.307 ^-1.347 ^0.002 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.307 ^-1.345 ^0 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.307 ^-1.343 ^-0.002 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.307 ^-1.342 ^-0.003 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.307 ^-1.342 ^-0.003 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.307 ^-1.342 ^-0.003 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.307 ^-1.342 ^-0.003 ~ ~