#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.327 ^-1.243 ^0.143 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.327 ^-1.247 ^0.138 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.327 ^-1.25 ^0.135 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.327 ^-1.251 ^0.134 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.327 ^-1.251 ^0.134 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.327 ^-1.251 ^0.134 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.327 ^-1.251 ^0.134 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.327 ^-1.264 ^0.122 ~ ~