#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 168 run tp @s ^-0.307 ^-1.335 ^-0.01 ~ ~
execute if score .this aj.frame matches 169 run tp @s ^-0.307 ^-1.339 ^-0.007 ~ ~
execute if score .this aj.frame matches 170 run tp @s ^-0.307 ^-1.341 ^-0.004 ~ ~
execute if score .this aj.frame matches 171 run tp @s ^-0.307 ^-1.342 ^-0.003 ~ ~
execute if score .this aj.frame matches 172 run tp @s ^-0.307 ^-1.342 ^-0.003 ~ ~
execute if score .this aj.frame matches 173 run tp @s ^-0.307 ^-1.342 ^-0.003 ~ ~
execute if score .this aj.frame matches 174 run tp @s ^-0.307 ^-1.342 ^-0.003 ~ ~
execute if score .this aj.frame matches 175 run tp @s ^-0.307 ^-1.357 ^0.012 ~ ~