#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 226 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 227 run data modify entity @s Pose.Head set value [0f,-1f,0f]
execute if score .this aj.frame matches 228 run data modify entity @s Pose.Head set value [0f,-4f,0f]
execute if score .this aj.frame matches 229 run data modify entity @s Pose.Head set value [0f,-7f,0f]
execute if score .this aj.frame matches 230 run data modify entity @s Pose.Head set value [0f,-10f,0f]
execute if score .this aj.frame matches 231 run data modify entity @s Pose.Head set value [0f,-13f,0f]