#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^0.327 ^-1.426 ^-0.04 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^0.327 ^-1.429 ^-0.044 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^0.327 ^-1.437 ^-0.052 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^0.327 ^-1.439 ^-0.053 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^0.327 ^-1.439 ^-0.053 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^0.327 ^-1.439 ^-0.053 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^0.327 ^-1.444 ^-0.059 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^0.327 ^-1.447 ^-0.061 ~ ~