#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [0f,-1.5f,0f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [0f,-4.5f,0f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [0f,-7.5f,0f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [0f,-10.5f,0f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [0f,-13.5f,0f]