#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-90f,0f,180f]