#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^-0.128 ^-1.717 ^0.082 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^-0.131 ^-1.717 ^0.079 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^-0.132 ^-1.717 ^0.078 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^-0.135 ^-1.717 ^0.075 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^-0.14 ^-1.717 ^0.07 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^-0.144 ^-1.717 ^0.066 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^-0.147 ^-1.717 ^0.063 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^-0.148 ^-1.717 ^0.062 ~ ~