#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 224 run tp @s ^0.327 ^-1.329 ^0.057 ~ ~
execute if score .this aj.frame matches 225 run tp @s ^0.327 ^-1.325 ^0.061 ~ ~
execute if score .this aj.frame matches 226 run tp @s ^0.327 ^-1.322 ^0.063 ~ ~
execute if score .this aj.frame matches 227 run tp @s ^0.327 ^-1.322 ^0.064 ~ ~
execute if score .this aj.frame matches 228 run tp @s ^0.327 ^-1.319 ^0.067 ~ ~
execute if score .this aj.frame matches 229 run tp @s ^0.327 ^-1.313 ^0.073 ~ ~
execute if score .this aj.frame matches 230 run tp @s ^0.327 ^-1.311 ^0.075 ~ ~
execute if score .this aj.frame matches 231 run tp @s ^0.327 ^-1.311 ^0.075 ~ ~