#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 144..151 run function crab_trap:animations/crab.move/tree/crab_export3_display_144-151
execute if score .this aj.frame matches 152..159 run function crab_trap:animations/crab.move/tree/crab_export3_display_152-159
execute if score .this aj.frame matches 160..167 run function crab_trap:animations/crab.move/tree/crab_export3_display_160-167
execute if score .this aj.frame matches 168..175 run function crab_trap:animations/crab.move/tree/crab_export3_display_168-175
execute if score .this aj.frame matches 176 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 184..191 run function crab_trap:animations/crab.move/tree/crab_export3_display_184-191