#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.307 ^-1.415 ^0.069 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.307 ^-1.413 ^0.068 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.307 ^-1.413 ^0.067 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.307 ^-1.411 ^0.066 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.307 ^-1.408 ^0.063 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.307 ^-1.405 ^0.06 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.307 ^-1.404 ^0.059 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.307 ^-1.404 ^0.059 ~ ~