#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 90 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 91 run data modify entity @s Pose.Head set value [0f,-0.5f,0f]
execute if score .this aj.frame matches 92 run data modify entity @s Pose.Head set value [0f,-3.5f,0f]
execute if score .this aj.frame matches 93 run data modify entity @s Pose.Head set value [0f,-6.5f,0f]
execute if score .this aj.frame matches 94 run data modify entity @s Pose.Head set value [0f,-9.5f,0f]
execute if score .this aj.frame matches 95 run data modify entity @s Pose.Head set value [0f,-12.5f,0f]