#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^-0.147 ^-1.717 ^0.062 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^-0.148 ^-1.717 ^0.061 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^-0.149 ^-1.717 ^0.061 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^-0.149 ^-1.717 ^0.061 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^-0.149 ^-1.717 ^0.061 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^-0.151 ^-1.717 ^0.06 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^-0.144 ^-1.717 ^0.067 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^-0.128 ^-1.717 ^0.083 ~ ~