#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 184 run tp @s ^-0.113 ^-1.717 ^0.098 ~ ~
execute if score .this aj.frame matches 185 run tp @s ^-0.112 ^-1.717 ^0.098 ~ ~
execute if score .this aj.frame matches 186 run tp @s ^-0.111 ^-1.717 ^0.099 ~ ~
execute if score .this aj.frame matches 187 run tp @s ^-0.109 ^-1.717 ^0.102 ~ ~
execute if score .this aj.frame matches 188 run tp @s ^-0.107 ^-1.717 ^0.103 ~ ~
execute if score .this aj.frame matches 189 run tp @s ^-0.107 ^-1.717 ^0.104 ~ ~
execute if score .this aj.frame matches 190 run tp @s ^-0.107 ^-1.717 ^0.104 ~ ~
execute if score .this aj.frame matches 191 run tp @s ^-0.107 ^-1.717 ^0.104 ~ ~