#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function crab_trap:animations/crab.move/tree/crab_export3_display_0-7
execute if score .this aj.frame matches 8..15 run function crab_trap:animations/crab.move/tree/crab_export3_display_8-15
execute if score .this aj.frame matches 16..23 run function crab_trap:animations/crab.move/tree/crab_export3_display_16-23
execute if score .this aj.frame matches 24..31 run function crab_trap:animations/crab.move/tree/crab_export3_display_24-31
execute if score .this aj.frame matches 40..47 run function crab_trap:animations/crab.move/tree/crab_export3_display_40-47
execute if score .this aj.frame matches 48..55 run function crab_trap:animations/crab.move/tree/crab_export3_display_48-55
execute if score .this aj.frame matches 56..63 run function crab_trap:animations/crab.move/tree/crab_export3_display_56-63