#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run tp @s ^0.327 ^-1.45 ^-0.065 ~ ~
execute if score .this aj.frame matches 121 run tp @s ^0.327 ^-1.454 ^-0.069 ~ ~
execute if score .this aj.frame matches 122 run tp @s ^0.327 ^-1.459 ^-0.073 ~ ~
execute if score .this aj.frame matches 123 run tp @s ^0.327 ^-1.463 ^-0.077 ~ ~
execute if score .this aj.frame matches 124 run tp @s ^0.327 ^-1.466 ^-0.08 ~ ~
execute if score .this aj.frame matches 125 run tp @s ^0.327 ^-1.467 ^-0.082 ~ ~
execute if score .this aj.frame matches 126 run tp @s ^0.327 ^-1.467 ^-0.082 ~ ~
execute if score .this aj.frame matches 127 run tp @s ^0.327 ^-1.467 ^-0.082 ~ ~