#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,-15f,0f]
execute if score .this aj.frame matches 48..55 run function crab_trap:animations/crab.move/tree/crab_export5_display_48-55