#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 152 run data modify entity @s Pose.Head set value [0f,-13.5f,0f]
execute if score .this aj.frame matches 153 run data modify entity @s Pose.Head set value [0f,-15f,0f]
execute if score .this aj.frame matches 155 run data modify entity @s Pose.Head set value [0f,-15f,0f]
execute if score .this aj.frame matches 156 run data modify entity @s Pose.Head set value [0f,-14.25f,0f]
execute if score .this aj.frame matches 157 run data modify entity @s Pose.Head set value [0f,-9.75f,0f]
execute if score .this aj.frame matches 158 run data modify entity @s Pose.Head set value [0f,-5.25f,0f]
execute if score .this aj.frame matches 159 run data modify entity @s Pose.Head set value [0f,-0.75f,0f]