#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64..71 run function crab_trap:animations/crab.move/tree/crab_export3_display_64-71
execute if score .this aj.frame matches 88..95 run function crab_trap:animations/crab.move/tree/crab_export3_display_88-95
execute if score .this aj.frame matches 96..103 run function crab_trap:animations/crab.move/tree/crab_export3_display_96-103
execute if score .this aj.frame matches 104..111 run function crab_trap:animations/crab.move/tree/crab_export3_display_104-111
execute if score .this aj.frame matches 112..119 run function crab_trap:animations/crab.move/tree/crab_export3_display_112-119
execute if score .this aj.frame matches 120 run data modify entity @s Pose.Head set value [0f,0f,0f]