#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 200 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 204 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 205 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.frame matches 206 run data modify entity @s Pose.Head set value [0f,5.5f,0f]
execute if score .this aj.frame matches 207 run data modify entity @s Pose.Head set value [0f,8.5f,0f]