#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 256 run tp @s ^0.327 ^-1.28 ^0.106 ~ ~
execute if score .this aj.frame matches 257 run tp @s ^0.327 ^-1.28 ^0.106 ~ ~
execute if score .this aj.frame matches 258 run tp @s ^0.327 ^-1.28 ^0.106 ~ ~
execute if score .this aj.frame matches 259 run tp @s ^0.327 ^-1.28 ^0.106 ~ ~
execute if score .this aj.frame matches 260 run tp @s ^0.327 ^-1.28 ^0.106 ~ ~
execute if score .this aj.frame matches 261 run tp @s ^0.327 ^-1.28 ^0.106 ~ ~
execute if score .this aj.frame matches 262 run tp @s ^0.327 ^-1.28 ^0.106 ~ ~
execute if score .this aj.frame matches 263 run tp @s ^0.327 ^-1.28 ^0.106 ~ ~