#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.307 ^-1.458 ^0.113 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.307 ^-1.467 ^0.122 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.307 ^-1.465 ^0.12 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.307 ^-1.454 ^0.108 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.307 ^-1.445 ^0.099 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.307 ^-1.443 ^0.098 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.307 ^-1.443 ^0.098 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.307 ^-1.443 ^0.098 ~ ~