#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 160 run tp @s ^-0.307 ^-1.318 ^-0.027 ~ ~
execute if score .this aj.frame matches 161 run tp @s ^-0.307 ^-1.321 ^-0.024 ~ ~
execute if score .this aj.frame matches 162 run tp @s ^-0.307 ^-1.323 ^-0.022 ~ ~
execute if score .this aj.frame matches 163 run tp @s ^-0.307 ^-1.325 ^-0.02 ~ ~
execute if score .this aj.frame matches 164 run tp @s ^-0.307 ^-1.327 ^-0.018 ~ ~
execute if score .this aj.frame matches 165 run tp @s ^-0.307 ^-1.329 ^-0.016 ~ ~
execute if score .this aj.frame matches 166 run tp @s ^-0.307 ^-1.33 ^-0.015 ~ ~
execute if score .this aj.frame matches 167 run tp @s ^-0.307 ^-1.331 ^-0.014 ~ ~