#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.327 ^-1.266 ^0.12 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.327 ^-1.27 ^0.116 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.327 ^-1.275 ^0.111 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.327 ^-1.279 ^0.107 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.327 ^-1.28 ^0.106 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.327 ^-1.28 ^0.106 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.327 ^-1.28 ^0.106 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0.327 ^-1.28 ^0.106 ~ ~