#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 216 run tp @s ^-0.307 ^-1.421 ^0.076 ~ ~
execute if score .this aj.frame matches 217 run tp @s ^-0.307 ^-1.422 ^0.077 ~ ~
execute if score .this aj.frame matches 218 run tp @s ^-0.307 ^-1.423 ^0.078 ~ ~
execute if score .this aj.frame matches 219 run tp @s ^-0.307 ^-1.424 ^0.079 ~ ~
execute if score .this aj.frame matches 220 run tp @s ^-0.307 ^-1.425 ^0.08 ~ ~
execute if score .this aj.frame matches 221 run tp @s ^-0.307 ^-1.426 ^0.08 ~ ~
execute if score .this aj.frame matches 222 run tp @s ^-0.307 ^-1.427 ^0.081 ~ ~
execute if score .this aj.frame matches 223 run tp @s ^-0.307 ^-1.427 ^0.082 ~ ~