#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^-0.307 ^-1.318 ^-0.028 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^-0.307 ^-1.315 ^-0.03 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^-0.307 ^-1.313 ^-0.032 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^-0.307 ^-1.31 ^-0.035 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^-0.307 ^-1.308 ^-0.037 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^-0.307 ^-1.306 ^-0.04 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^-0.307 ^-1.303 ^-0.042 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^-0.307 ^-1.301 ^-0.044 ~ ~