#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.134 ^-1.717 ^0.076 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.138 ^-1.717 ^0.072 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.142 ^-1.717 ^0.068 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.146 ^-1.717 ^0.064 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.148 ^-1.717 ^0.062 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.147 ^-1.717 ^0.062 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.148 ^-1.717 ^0.062 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.149 ^-1.717 ^0.061 ~ ~