#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 256..263 run function crab_trap:animations/crab.move/tree/group_root_256-263
execute if score .this aj.frame matches 264..271 run function crab_trap:animations/crab.move/tree/group_root_264-271
execute if score .this aj.frame matches 272..279 run function crab_trap:animations/crab.move/tree/group_root_272-279