#Project generated by Animated Java (https://animated-java.dev/)

schedule function otc_crab_trap:model/animation_loop 1t
scoreboard players set .aj.anim_loop aj.OtcFishingCrabTrab.animating 1
scoreboard players set .aj.animation aj.OtcFishingCrabTrab.animating 0
execute as @e[type=minecraft:marker,tag=aj.OtcFishingCrabTrab.root] run function otc_crab_trap:model/zzz/execute/17
execute if score .aj.animation aj.OtcFishingCrabTrab.animating matches 0 run function otc_crab_trap:model/zzz/execute/18
