#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.OtcFishingCrabTrab.root] at @s rotated ~ 0 run function otc_crab_trap:model/zzz/conditional/2
execute if score #execute aj.i matches 0 run function otc_crab_trap:model/zzz/conditional/3