#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.crab_trap.crab.move.loopMode matches 0 run function crab_trap:animations/crab.move/stop
execute if score @s aj.crab_trap.crab.move.loopMode matches 1 run function crab_trap:animations/crab.move/pause
execute if score @s aj.crab_trap.crab.move.loopMode matches 2 run function crab_trap:animations/crab.move/zzz/execute/19