#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.crab_trap.root] at @s run function crab_trap:animations/crab.move/zzz/conditional/6
execute if score #execute aj.i matches 0 run function crab_trap:animations/crab.move/zzz/conditional/7