#Project generated by Animated Java (https://animated-java.dev/)

summon minecraft:marker ~ ~ ~ {Tags:['OtcFishingCrabTrab','new','aj.OtcFishingCrabTrab','aj.OtcFishingCrabTrab.root','OtcFishingCrabTrabCatch']}
execute as @e[type=minecraft:marker,tag=aj.OtcFishingCrabTrab.root,tag=new,distance=..1,limit=1] rotated ~ 0 run function otc_crab_trap:model/summon/zzz/execute/5
function otc_crab_trap:model/assert_animation_flags