#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.crab_trap.anim.crab.move
execute if score .aj.anim_loop aj.crab_trap.animating matches 0 run function crab_trap:animation_loop
scoreboard players set #execute aj.i 1