#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~