#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[type=minecraft:area_effect_cloud] run function otc_crab_trap:model/animations/crab.empty/tree/root_bone_name
execute if entity @s[type=minecraft:armor_stand] run function otc_crab_trap:model/animations/crab.empty/tree/display_bone_name