#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set # aj.i 1
execute at @s as @e[type=#otc_crab_trap:bone_entities,tag=aj.OtcFishingCrabTrabCrabTrap.bone] if score @s aj.id = .this aj.id run function otc_crab_trap:model/zzz/execute/14