#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.OtcFishingCrabTrab.anim.crab.move] at @s run function otc_crab_trap:model/animations/crab.move/next_frame
execute if entity @s[tag=aj.OtcFishingCrabTrab.anim.crab.empty] at @s run function otc_crab_trap:model/animations/crab.empty/next_frame
scoreboard players operation @s aj.OtcFishingCrabTrab.animating = .aj.animation aj.OtcFishingCrabTrab.animating
