#Project generated by Animated Java (https://animated-java.dev/)

tp @s ~ ~ ~ ~ ~
scoreboard players operation .this aj.id = @s aj.id
scoreboard players operation .this aj.frame = @s aj.frame
scoreboard players set # aj.i 0
execute if entity @s[tag=aj.crab_trap.anim.crab.move] run function crab_trap:zzz/execute/10
execute if entity @s[tag=aj.crab_trap.anim.crab.empty] run function crab_trap:zzz/execute/13
execute if score # aj.i matches 0 run function crab_trap:zzz/execute/16
scoreboard players set #execute aj.i 1