#Project generated by Animated Java (https://animated-java.dev/)

summon minecraft:marker ~ ~ ~ {Tags:['otc_fishing_crab_trap','new','aj.crab_trap','aj.crab_trap.root']}
execute as @e[type=minecraft:marker,tag=aj.crab_trap.root,tag=new,distance=..1,limit=1] rotated ~ 0 run function crab_trap:summon/zzz/execute/5
function crab_trap:assert_animation_flags
