#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 16..23 run function otc_crab_trap:model/animations/crab.move/tree/crab_export_display_16-23