#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.307 ^-1.384 ^0.039 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.307 ^-1.382 ^0.037 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.307 ^-1.379 ^0.034 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.307 ^-1.377 ^0.032 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.307 ^-1.375 ^0.03 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.307 ^-1.372 ^0.027 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.307 ^-1.37 ^0.025 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.307 ^-1.368 ^0.023 ~ ~