#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 160 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 164 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 165 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.frame matches 166 run data modify entity @s Pose.Head set value [0f,5.5f,0f]
execute if score .this aj.frame matches 167 run data modify entity @s Pose.Head set value [0f,8.5f,0f]