#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^0.327 ^-1.369 ^0.017 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^0.327 ^-1.37 ^0.016 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^0.327 ^-1.37 ^0.016 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^0.327 ^-1.37 ^0.016 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^0.327 ^-1.37 ^0.016 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^0.327 ^-1.387 ^-0.002 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^0.327 ^-1.387 ^-0.002 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^0.327 ^-1.387 ^-0.002 ~ ~