#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run tp @s ^0.327 ^-1.337 ^0.049 ~ ~
execute if score .this aj.frame matches 89 run tp @s ^0.327 ^-1.341 ^0.045 ~ ~
execute if score .this aj.frame matches 90 run tp @s ^0.327 ^-1.342 ^0.043 ~ ~
execute if score .this aj.frame matches 91 run tp @s ^0.327 ^-1.344 ^0.042 ~ ~
execute if score .this aj.frame matches 92 run tp @s ^0.327 ^-1.352 ^0.033 ~ ~
execute if score .this aj.frame matches 93 run tp @s ^0.327 ^-1.356 ^0.03 ~ ~
execute if score .this aj.frame matches 94 run tp @s ^0.327 ^-1.357 ^0.029 ~ ~
execute if score .this aj.frame matches 95 run tp @s ^0.327 ^-1.363 ^0.023 ~ ~