#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 116 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 117 run data modify entity @s Pose.Head set value [-180f,15f,180f]