#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.327 ^-1.28 ^0.106 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.327 ^-1.279 ^0.107 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.327 ^-1.275 ^0.111 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.327 ^-1.27 ^0.116 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.327 ^-1.266 ^0.12 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.327 ^-1.264 ^0.122 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.327 ^-1.263 ^0.123 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.327 ^-1.259 ^0.127 ~ ~