#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.307 ^-1.43 ^0.085 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.307 ^-1.429 ^0.084 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.307 ^-1.427 ^0.082 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.307 ^-1.425 ^0.079 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.307 ^-1.422 ^0.077 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.307 ^-1.42 ^0.075 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.307 ^-1.418 ^0.073 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.307 ^-1.416 ^0.071 ~ ~