#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 152 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 153 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 154 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 155 run tp @s ^-0.105 ^-1.717 ^0.106 ~ ~
execute if score .this aj.frame matches 156 run tp @s ^-0.106 ^-1.717 ^0.105 ~ ~
execute if score .this aj.frame matches 157 run tp @s ^-0.108 ^-1.717 ^0.102 ~ ~
execute if score .this aj.frame matches 158 run tp @s ^-0.111 ^-1.717 ^0.099 ~ ~
execute if score .this aj.frame matches 159 run tp @s ^-0.115 ^-1.717 ^0.096 ~ ~