#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 200 run tp @s ^0.327 ^-1.405 ^-0.019 ~ ~
execute if score .this aj.frame matches 201 run tp @s ^0.327 ^-1.403 ^-0.018 ~ ~
execute if score .this aj.frame matches 202 run tp @s ^0.327 ^-1.4 ^-0.014 ~ ~
execute if score .this aj.frame matches 203 run tp @s ^0.327 ^-1.397 ^-0.011 ~ ~
execute if score .this aj.frame matches 204 run tp @s ^0.327 ^-1.392 ^-0.007 ~ ~
execute if score .this aj.frame matches 205 run tp @s ^0.327 ^-1.388 ^-0.002 ~ ~
execute if score .this aj.frame matches 206 run tp @s ^0.327 ^-1.384 ^0.001 ~ ~
execute if score .this aj.frame matches 207 run tp @s ^0.327 ^-1.381 ^0.005 ~ ~