#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 89 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 90 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 91 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 92 run tp @s ^-0.105 ^-1.717 ^0.106 ~ ~
execute if score .this aj.frame matches 93 run tp @s ^-0.106 ^-1.717 ^0.104 ~ ~
execute if score .this aj.frame matches 94 run tp @s ^-0.109 ^-1.717 ^0.101 ~ ~
execute if score .this aj.frame matches 95 run tp @s ^-0.113 ^-1.717 ^0.098 ~ ~