#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 168 run tp @s ^-0.128 ^-1.717 ^0.082 ~ ~
execute if score .this aj.frame matches 169 run tp @s ^-0.131 ^-1.717 ^0.079 ~ ~
execute if score .this aj.frame matches 170 run tp @s ^-0.134 ^-1.717 ^0.076 ~ ~
execute if score .this aj.frame matches 171 run tp @s ^-0.138 ^-1.717 ^0.072 ~ ~
execute if score .this aj.frame matches 172 run tp @s ^-0.142 ^-1.717 ^0.068 ~ ~
execute if score .this aj.frame matches 173 run tp @s ^-0.146 ^-1.717 ^0.064 ~ ~
execute if score .this aj.frame matches 174 run tp @s ^-0.148 ^-1.717 ^0.062 ~ ~
execute if score .this aj.frame matches 175 run tp @s ^-0.147 ^-1.717 ^0.062 ~ ~