#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 248 run data modify entity @s Pose.Head set value [0f,11.6667f,0f]
execute if score .this aj.frame matches 249 run data modify entity @s Pose.Head set value [0f,10f,0f]
execute if score .this aj.frame matches 250 run data modify entity @s Pose.Head set value [0f,8.3333f,0f]
execute if score .this aj.frame matches 251 run data modify entity @s Pose.Head set value [0f,6.6667f,0f]
execute if score .this aj.frame matches 252 run data modify entity @s Pose.Head set value [0f,5f,0f]
execute if score .this aj.frame matches 253 run data modify entity @s Pose.Head set value [0f,3.3333f,0f]
execute if score .this aj.frame matches 254 run data modify entity @s Pose.Head set value [0f,1.6667f,0f]
execute if score .this aj.frame matches 255 run data modify entity @s Pose.Head set value [0f,0f,0f]