#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 147 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 148 run data modify entity @s Pose.Head set value [0f,-1.5f,0f]
execute if score .this aj.frame matches 149 run data modify entity @s Pose.Head set value [0f,-4.5f,0f]
execute if score .this aj.frame matches 150 run data modify entity @s Pose.Head set value [0f,-7.5f,0f]
execute if score .this aj.frame matches 151 run data modify entity @s Pose.Head set value [0f,-10.5f,0f]