#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 240 run tp @s ^-0.151 ^-1.717 ^0.059 ~ ~
execute if score .this aj.frame matches 241 run tp @s ^-0.147 ^-1.717 ^0.063 ~ ~
execute if score .this aj.frame matches 242 run tp @s ^-0.134 ^-1.717 ^0.077 ~ ~
execute if score .this aj.frame matches 243 run tp @s ^-0.118 ^-1.717 ^0.092 ~ ~
execute if score .this aj.frame matches 244 run tp @s ^-0.113 ^-1.717 ^0.098 ~ ~
execute if score .this aj.frame matches 245 run tp @s ^-0.112 ^-1.717 ^0.098 ~ ~
execute if score .this aj.frame matches 246 run tp @s ^-0.111 ^-1.717 ^0.099 ~ ~
execute if score .this aj.frame matches 247 run tp @s ^-0.109 ^-1.717 ^0.102 ~ ~