#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 232 run data modify entity @s Pose.Head set value [0f,-15f,0f]
execute if score .this aj.frame matches 235 run data modify entity @s Pose.Head set value [0f,-15f,0f]
execute if score .this aj.frame matches 236 run data modify entity @s Pose.Head set value [0f,-10.5f,0f]
execute if score .this aj.frame matches 237 run data modify entity @s Pose.Head set value [0f,-6f,0f]
execute if score .this aj.frame matches 238 run data modify entity @s Pose.Head set value [0f,-1.5f,0f]
execute if score .this aj.frame matches 239 run data modify entity @s Pose.Head set value [0f,0f,0f]