#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 184 run tp @s ^0.327 ^-1.454 ^-0.068 ~ ~
execute if score .this aj.frame matches 185 run tp @s ^0.327 ^-1.45 ^-0.064 ~ ~
execute if score .this aj.frame matches 186 run tp @s ^0.327 ^-1.447 ^-0.062 ~ ~
execute if score .this aj.frame matches 187 run tp @s ^0.327 ^-1.447 ^-0.061 ~ ~
execute if score .this aj.frame matches 188 run tp @s ^0.327 ^-1.444 ^-0.058 ~ ~
execute if score .this aj.frame matches 189 run tp @s ^0.327 ^-1.438 ^-0.052 ~ ~
execute if score .this aj.frame matches 190 run tp @s ^0.327 ^-1.436 ^-0.05 ~ ~
execute if score .this aj.frame matches 191 run tp @s ^0.327 ^-1.436 ^-0.05 ~ ~