#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 232 run tp @s ^-0.142 ^-1.717 ^0.068 ~ ~
execute if score .this aj.frame matches 233 run tp @s ^-0.146 ^-1.717 ^0.064 ~ ~
execute if score .this aj.frame matches 234 run tp @s ^-0.148 ^-1.717 ^0.062 ~ ~
execute if score .this aj.frame matches 235 run tp @s ^-0.147 ^-1.717 ^0.062 ~ ~
execute if score .this aj.frame matches 236 run tp @s ^-0.148 ^-1.717 ^0.062 ~ ~
execute if score .this aj.frame matches 237 run tp @s ^-0.149 ^-1.717 ^0.061 ~ ~
execute if score .this aj.frame matches 238 run tp @s ^-0.149 ^-1.717 ^0.061 ~ ~
execute if score .this aj.frame matches 239 run tp @s ^-0.149 ^-1.717 ^0.061 ~ ~