#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.327 ^-1.231 ^0.155 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.327 ^-1.227 ^0.159 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.327 ^-1.222 ^0.164 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.327 ^-1.219 ^0.167 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.327 ^-1.217 ^0.168 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.327 ^-1.217 ^0.168 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.327 ^-1.217 ^0.168 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.327 ^-1.217 ^0.168 ~ ~