#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 232 run tp @s ^0.327 ^-1.311 ^0.075 ~ ~
execute if score .this aj.frame matches 233 run tp @s ^0.327 ^-1.311 ^0.075 ~ ~
execute if score .this aj.frame matches 234 run tp @s ^0.327 ^-1.311 ^0.075 ~ ~
execute if score .this aj.frame matches 235 run tp @s ^0.327 ^-1.296 ^0.09 ~ ~
execute if score .this aj.frame matches 236 run tp @s ^0.327 ^-1.296 ^0.09 ~ ~
execute if score .this aj.frame matches 237 run tp @s ^0.327 ^-1.296 ^0.09 ~ ~
execute if score .this aj.frame matches 238 run tp @s ^0.327 ^-1.296 ^0.09 ~ ~
execute if score .this aj.frame matches 239 run tp @s ^0.327 ^-1.296 ^0.09 ~ ~