#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 144 run tp @s ^-0.307 ^-1.279 ^-0.066 ~ ~
execute if score .this aj.frame matches 145 run tp @s ^-0.307 ^-1.279 ^-0.066 ~ ~
execute if score .this aj.frame matches 146 run tp @s ^-0.307 ^-1.279 ^-0.066 ~ ~
execute if score .this aj.frame matches 147 run tp @s ^-0.307 ^-1.289 ^-0.056 ~ ~
execute if score .this aj.frame matches 148 run tp @s ^-0.307 ^-1.291 ^-0.055 ~ ~
execute if score .this aj.frame matches 149 run tp @s ^-0.307 ^-1.293 ^-0.053 ~ ~
execute if score .this aj.frame matches 150 run tp @s ^-0.307 ^-1.295 ^-0.05 ~ ~
execute if score .this aj.frame matches 151 run tp @s ^-0.307 ^-1.297 ^-0.048 ~ ~