#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 256..263 run function otc_crab_trap:model/animations/crab.move/tree/crab_export2_root_256-263
execute if score .this aj.frame matches 264..271 run function otc_crab_trap:model/animations/crab.move/tree/crab_export2_root_264-271
execute if score .this aj.frame matches 272..279 run function otc_crab_trap:model/animations/crab.move/tree/crab_export2_root_272-279