#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run tp @s ^-0.107 ^-1.717 ^0.104 ~ ~
execute if score .this aj.frame matches 129 run tp @s ^-0.107 ^-1.717 ^0.104 ~ ~
execute if score .this aj.frame matches 130 run tp @s ^-0.098 ^-1.717 ^0.112 ~ ~
execute if score .this aj.frame matches 131 run tp @s ^-0.096 ^-1.717 ^0.114 ~ ~
execute if score .this aj.frame matches 132 run tp @s ^-0.094 ^-1.717 ^0.116 ~ ~
execute if score .this aj.frame matches 133 run tp @s ^-0.093 ^-1.717 ^0.118 ~ ~
execute if score .this aj.frame matches 134 run tp @s ^-0.091 ^-1.717 ^0.119 ~ ~
execute if score .this aj.frame matches 135 run tp @s ^-0.09 ^-1.717 ^0.121 ~ ~