#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 224 run tp @s ^-0.307 ^-1.428 ^0.083 ~ ~
execute if score .this aj.frame matches 225 run tp @s ^-0.307 ^-1.429 ^0.084 ~ ~
execute if score .this aj.frame matches 226 run tp @s ^-0.307 ^-1.43 ^0.084 ~ ~
execute if score .this aj.frame matches 227 run tp @s ^-0.307 ^-1.43 ^0.085 ~ ~
execute if score .this aj.frame matches 228 run tp @s ^-0.307 ^-1.431 ^0.086 ~ ~
execute if score .this aj.frame matches 229 run tp @s ^-0.307 ^-1.431 ^0.086 ~ ~
execute if score .this aj.frame matches 230 run tp @s ^-0.307 ^-1.431 ^0.086 ~ ~
execute if score .this aj.frame matches 231 run tp @s ^-0.307 ^-1.434 ^0.089 ~ ~