#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 192..199 run function otc_crab_trap:model/animations/crab.move/tree/crab_export3_display_192-199
execute if score .this aj.frame matches 200..207 run function otc_crab_trap:model/animations/crab.move/tree/crab_export3_display_200-207
execute if score .this aj.frame matches 208..215 run function otc_crab_trap:model/animations/crab.move/tree/crab_export3_display_208-215
execute if score .this aj.frame matches 216 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 224..231 run function otc_crab_trap:model/animations/crab.move/tree/crab_export3_display_224-231
execute if score .this aj.frame matches 232..239 run function otc_crab_trap:model/animations/crab.move/tree/crab_export3_display_232-239
execute if score .this aj.frame matches 240..247 run function otc_crab_trap:model/animations/crab.move/tree/crab_export3_display_240-247
execute if score .this aj.frame matches 248..255 run function otc_crab_trap:model/animations/crab.move/tree/crab_export3_display_248-255