#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [0f,11.3889f,0f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [0f,9.7222f,0f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [0f,8.0556f,0f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [0f,6.3889f,0f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [0f,4.7222f,0f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [0f,3.0556f,0f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [0f,1.3889f,0f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [0f,0f,0f]