#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 159 run data modify entity @s Pose.Head set value [-90f,0f,180f]
execute if score .this aj.frame matches 160 run data modify entity @s Pose.Head set value [0f,0f,0f]