#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 176 run tp @s ^-0.307 ^-1.358 ^0.013 ~ ~
execute if score .this aj.frame matches 177 run tp @s ^-0.307 ^-1.36 ^0.015 ~ ~
execute if score .this aj.frame matches 178 run tp @s ^-0.307 ^-1.362 ^0.017 ~ ~
execute if score .this aj.frame matches 179 run tp @s ^-0.307 ^-1.364 ^0.019 ~ ~
execute if score .this aj.frame matches 180 run tp @s ^-0.307 ^-1.366 ^0.021 ~ ~
execute if score .this aj.frame matches 181 run tp @s ^-0.307 ^-1.368 ^0.023 ~ ~
execute if score .this aj.frame matches 182 run tp @s ^-0.307 ^-1.371 ^0.025 ~ ~
execute if score .this aj.frame matches 183 run tp @s ^-0.307 ^-1.373 ^0.028 ~ ~