#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [0f,-15f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [0f,-12f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [0f,-7.5f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [0f,-3f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [0f,0f,0f]