#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^-0.149 ^-1.717 ^0.061 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-0.149 ^-1.717 ^0.061 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^-0.151 ^-1.717 ^0.059 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^-0.147 ^-1.717 ^0.063 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-0.134 ^-1.717 ^0.077 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-0.118 ^-1.717 ^0.092 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-0.113 ^-1.717 ^0.098 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-0.112 ^-1.717 ^0.098 ~ ~