#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [0f,1f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [0f,4f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [0f,7f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [0f,10f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [0f,12.2222f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [0f,10.5556f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [0f,8.8889f,0f]