#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [0f,7.2222f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [0f,5.5556f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [0f,3.8889f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [0f,2.2222f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [0f,0.5556f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [0f,0f,0f]