#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 184 run tp @s ^-0.307 ^-1.375 ^0.03 ~ ~
execute if score .this aj.frame matches 185 run tp @s ^-0.307 ^-1.377 ^0.032 ~ ~
execute if score .this aj.frame matches 186 run tp @s ^-0.307 ^-1.38 ^0.034 ~ ~
execute if score .this aj.frame matches 187 run tp @s ^-0.307 ^-1.382 ^0.037 ~ ~
execute if score .this aj.frame matches 188 run tp @s ^-0.307 ^-1.384 ^0.039 ~ ~
execute if score .this aj.frame matches 189 run tp @s ^-0.307 ^-1.386 ^0.041 ~ ~
execute if score .this aj.frame matches 190 run tp @s ^-0.307 ^-1.388 ^0.043 ~ ~
execute if score .this aj.frame matches 191 run tp @s ^-0.307 ^-1.39 ^0.045 ~ ~