#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 243 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 244 run data modify entity @s Pose.Head set value [0f,2f,0f]
execute if score .this aj.frame matches 245 run data modify entity @s Pose.Head set value [0f,5f,0f]
execute if score .this aj.frame matches 246 run data modify entity @s Pose.Head set value [0f,8f,0f]
execute if score .this aj.frame matches 247 run data modify entity @s Pose.Head set value [0f,11f,0f]