#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 208 run data modify entity @s Pose.Head set value [0f,11.5f,0f]
execute if score .this aj.frame matches 209 run data modify entity @s Pose.Head set value [0f,11.3889f,0f]
execute if score .this aj.frame matches 210 run data modify entity @s Pose.Head set value [0f,9.7222f,0f]
execute if score .this aj.frame matches 211 run data modify entity @s Pose.Head set value [0f,8.0556f,0f]
execute if score .this aj.frame matches 212 run data modify entity @s Pose.Head set value [0f,6.3889f,0f]
execute if score .this aj.frame matches 213 run data modify entity @s Pose.Head set value [0f,4.7222f,0f]
execute if score .this aj.frame matches 214 run data modify entity @s Pose.Head set value [0f,3.0556f,0f]
execute if score .this aj.frame matches 215 run data modify entity @s Pose.Head set value [0f,1.3889f,0f]