#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 208 run tp @s ^-0.307 ^-1.414 ^0.069 ~ ~
execute if score .this aj.frame matches 209 run tp @s ^-0.307 ^-1.415 ^0.07 ~ ~
execute if score .this aj.frame matches 210 run tp @s ^-0.307 ^-1.416 ^0.071 ~ ~
execute if score .this aj.frame matches 211 run tp @s ^-0.307 ^-1.417 ^0.071 ~ ~
execute if score .this aj.frame matches 212 run tp @s ^-0.307 ^-1.418 ^0.072 ~ ~
execute if score .this aj.frame matches 213 run tp @s ^-0.307 ^-1.418 ^0.073 ~ ~
execute if score .this aj.frame matches 214 run tp @s ^-0.307 ^-1.419 ^0.074 ~ ~
execute if score .this aj.frame matches 215 run tp @s ^-0.307 ^-1.42 ^0.075 ~ ~