#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 187 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 188 run data modify entity @s Pose.Head set value [0f,-1.5f,0f]
execute if score .this aj.frame matches 189 run data modify entity @s Pose.Head set value [0f,-4.5f,0f]
execute if score .this aj.frame matches 190 run data modify entity @s Pose.Head set value [0f,-7.5f,0f]
execute if score .this aj.frame matches 191 run data modify entity @s Pose.Head set value [0f,-10.5f,0f]