#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 176 run tp @s ^-0.148 ^-1.717 ^0.062 ~ ~
execute if score .this aj.frame matches 177 run tp @s ^-0.149 ^-1.717 ^0.061 ~ ~
execute if score .this aj.frame matches 178 run tp @s ^-0.149 ^-1.717 ^0.061 ~ ~
execute if score .this aj.frame matches 179 run tp @s ^-0.149 ^-1.717 ^0.061 ~ ~
execute if score .this aj.frame matches 180 run tp @s ^-0.151 ^-1.717 ^0.059 ~ ~
execute if score .this aj.frame matches 181 run tp @s ^-0.147 ^-1.717 ^0.063 ~ ~
execute if score .this aj.frame matches 182 run tp @s ^-0.134 ^-1.717 ^0.077 ~ ~
execute if score .this aj.frame matches 183 run tp @s ^-0.118 ^-1.717 ^0.092 ~ ~