#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run tp @s ^-0.307 ^-1.283 ^-0.063 ~ ~
execute if score .this aj.frame matches 89 run tp @s ^-0.307 ^-1.28 ^-0.065 ~ ~
execute if score .this aj.frame matches 90 run tp @s ^-0.307 ^-1.279 ^-0.066 ~ ~
execute if score .this aj.frame matches 91 run tp @s ^-0.307 ^-1.279 ^-0.066 ~ ~
execute if score .this aj.frame matches 92 run tp @s ^-0.307 ^-1.279 ^-0.066 ~ ~
execute if score .this aj.frame matches 93 run tp @s ^-0.307 ^-1.279 ^-0.066 ~ ~
execute if score .this aj.frame matches 94 run tp @s ^-0.307 ^-1.279 ^-0.066 ~ ~
execute if score .this aj.frame matches 95 run tp @s ^-0.307 ^-1.279 ^-0.066 ~ ~