#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.307 ^-1.404 ^0.059 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.307 ^-1.404 ^0.059 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.307 ^-1.404 ^0.059 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.307 ^-1.395 ^0.05 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.307 ^-1.393 ^0.048 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.307 ^-1.391 ^0.046 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.307 ^-1.389 ^0.044 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.307 ^-1.387 ^0.041 ~ ~