#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 136 run tp @s ^-0.307 ^-1.266 ^-0.079 ~ ~
execute if score .this aj.frame matches 137 run tp @s ^-0.307 ^-1.268 ^-0.078 ~ ~
execute if score .this aj.frame matches 138 run tp @s ^-0.307 ^-1.269 ^-0.076 ~ ~
execute if score .this aj.frame matches 139 run tp @s ^-0.307 ^-1.272 ^-0.073 ~ ~
execute if score .this aj.frame matches 140 run tp @s ^-0.307 ^-1.275 ^-0.07 ~ ~
execute if score .this aj.frame matches 141 run tp @s ^-0.307 ^-1.278 ^-0.068 ~ ~
execute if score .this aj.frame matches 142 run tp @s ^-0.307 ^-1.279 ^-0.066 ~ ~
execute if score .this aj.frame matches 143 run tp @s ^-0.307 ^-1.279 ^-0.066 ~ ~