#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^-0.307 ^-1.299 ^-0.047 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^-0.307 ^-1.296 ^-0.049 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^-0.307 ^-1.294 ^-0.051 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^-0.307 ^-1.292 ^-0.053 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^-0.307 ^-1.29 ^-0.055 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^-0.307 ^-1.289 ^-0.056 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^-0.307 ^-1.288 ^-0.057 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^-0.307 ^-1.286 ^-0.06 ~ ~