#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 149 run data modify entity @s Pose.Head set value [-180f,15f,180f]
execute if score .this aj.frame matches 150 run data modify entity @s Pose.Head set value [0f,-15f,0f]