#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.105 ^-1.717 ^0.106 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.106 ^-1.717 ^0.105 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.108 ^-1.717 ^0.102 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.111 ^-1.717 ^0.099 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.115 ^-1.717 ^0.096 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.117 ^-1.717 ^0.093 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.118 ^-1.717 ^0.092 ~ ~