#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^-0.307 ^-1.365 ^0.02 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-0.307 ^-1.363 ^0.018 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^-0.307 ^-1.361 ^0.016 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^-0.307 ^-1.359 ^0.014 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-0.307 ^-1.357 ^0.012 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-0.307 ^-1.357 ^0.011 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-0.307 ^-1.355 ^0.01 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-0.307 ^-1.353 ^0.008 ~ ~