#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [0f,5.5f,0f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [0f,8.5f,0f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [0f,11.5f,0f]