#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^-0.307 ^-1.233 ^-0.112 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^-0.307 ^-1.231 ^-0.114 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^-0.307 ^-1.229 ^-0.117 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^-0.307 ^-1.226 ^-0.119 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^-0.307 ^-1.224 ^-0.121 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^-0.307 ^-1.222 ^-0.123 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^-0.307 ^-1.22 ^-0.125 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^-0.307 ^-1.218 ^-0.127 ~ ~