#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 272 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 273 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 274 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 275 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 276 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 277 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 278 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~
execute if score .this aj.frame matches 279 run tp @s ^-0.089 ^-1.717 ^0.122 ~ ~