#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function otc_crab_trap:model/animations/crab.move/tree/crab_export_display_0-63
execute if score .this aj.frame matches 128..191 run function otc_crab_trap:model/animations/crab.move/tree/crab_export_display_128-191
execute if score .this aj.frame matches 279 run data modify entity @s Pose.Head set value [0f,0f,0f]