#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 192 run tp @s ^-0.307 ^-1.392 ^0.047 ~ ~
execute if score .this aj.frame matches 193 run tp @s ^-0.307 ^-1.394 ^0.049 ~ ~
execute if score .this aj.frame matches 194 run tp @s ^-0.307 ^-1.396 ^0.05 ~ ~
execute if score .this aj.frame matches 195 run tp @s ^-0.307 ^-1.396 ^0.051 ~ ~
execute if score .this aj.frame matches 196 run tp @s ^-0.307 ^-1.397 ^0.052 ~ ~
execute if score .this aj.frame matches 197 run tp @s ^-0.307 ^-1.399 ^0.054 ~ ~
execute if score .this aj.frame matches 198 run tp @s ^-0.307 ^-1.401 ^0.056 ~ ~
execute if score .this aj.frame matches 199 run tp @s ^-0.307 ^-1.403 ^0.058 ~ ~