#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^-0.307 ^-1.268 ^-0.078 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^-0.307 ^-1.266 ^-0.079 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^-0.307 ^-1.264 ^-0.081 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^-0.307 ^-1.262 ^-0.083 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^-0.307 ^-1.26 ^-0.085 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^-0.307 ^-1.258 ^-0.087 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^-0.307 ^-1.256 ^-0.09 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^-0.307 ^-1.253 ^-0.092 ~ ~