#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run data modify entity @s Pose.Head set value [0f,-15f,0f]
execute if score .this aj.frame matches 99 run data modify entity @s Pose.Head set value [0f,-15f,0f]
execute if score .this aj.frame matches 100 run data modify entity @s Pose.Head set value [0f,-11.25f,0f]
execute if score .this aj.frame matches 101 run data modify entity @s Pose.Head set value [0f,-6.75f,0f]
execute if score .this aj.frame matches 102 run data modify entity @s Pose.Head set value [0f,-2.25f,0f]
execute if score .this aj.frame matches 103 run data modify entity @s Pose.Head set value [0f,0f,0f]