#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run tp @s ^-0.307 ^-1.228 ^-0.117 ~ ~
execute if score .this aj.frame matches 129 run tp @s ^-0.307 ^-1.233 ^-0.112 ~ ~
execute if score .this aj.frame matches 130 run tp @s ^-0.307 ^-1.238 ^-0.107 ~ ~
execute if score .this aj.frame matches 131 run tp @s ^-0.307 ^-1.243 ^-0.102 ~ ~
execute if score .this aj.frame matches 132 run tp @s ^-0.307 ^-1.248 ^-0.097 ~ ~
execute if score .this aj.frame matches 133 run tp @s ^-0.307 ^-1.253 ^-0.092 ~ ~
execute if score .this aj.frame matches 134 run tp @s ^-0.307 ^-1.258 ^-0.087 ~ ~
execute if score .this aj.frame matches 135 run tp @s ^-0.307 ^-1.263 ^-0.082 ~ ~