#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 216 run tp @s ^-0.106 ^-1.717 ^0.105 ~ ~
execute if score .this aj.frame matches 217 run tp @s ^-0.108 ^-1.717 ^0.102 ~ ~
execute if score .this aj.frame matches 218 run tp @s ^-0.111 ^-1.717 ^0.099 ~ ~
execute if score .this aj.frame matches 219 run tp @s ^-0.115 ^-1.717 ^0.096 ~ ~
execute if score .this aj.frame matches 220 run tp @s ^-0.117 ^-1.717 ^0.093 ~ ~
execute if score .this aj.frame matches 221 run tp @s ^-0.118 ^-1.717 ^0.092 ~ ~
execute if score .this aj.frame matches 222 run tp @s ^-0.121 ^-1.717 ^0.089 ~ ~
execute if score .this aj.frame matches 223 run tp @s ^-0.128 ^-1.717 ^0.082 ~ ~