#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 176 run tp @s ^0.327 ^-1.467 ^-0.082 ~ ~
execute if score .this aj.frame matches 177 run tp @s ^0.327 ^-1.467 ^-0.082 ~ ~
execute if score .this aj.frame matches 178 run tp @s ^0.327 ^-1.467 ^-0.082 ~ ~
execute if score .this aj.frame matches 179 run tp @s ^0.327 ^-1.467 ^-0.082 ~ ~
execute if score .this aj.frame matches 180 run tp @s ^0.327 ^-1.467 ^-0.082 ~ ~
execute if score .this aj.frame matches 181 run tp @s ^0.327 ^-1.466 ^-0.08 ~ ~
execute if score .this aj.frame matches 182 run tp @s ^0.327 ^-1.463 ^-0.077 ~ ~
execute if score .this aj.frame matches 183 run tp @s ^0.327 ^-1.459 ^-0.073 ~ ~