#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^0.327 ^-1.387 ^-0.002 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^0.327 ^-1.405 ^-0.019 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^0.327 ^-1.406 ^-0.02 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^0.327 ^-1.41 ^-0.024 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^0.327 ^-1.414 ^-0.028 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^0.327 ^-1.418 ^-0.033 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^0.327 ^-1.422 ^-0.037 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^0.327 ^-1.425 ^-0.04 ~ ~