#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.OtcFishingCrabTrab.bone.group2] run function otc_crab_trap:model/animations/crab.move/tree/group2_display_top
execute if entity @s[tag=aj.OtcFishingCrabTrab.bone.group3] run function otc_crab_trap:model/animations/crab.move/tree/group3_display_top
execute if entity @s[tag=aj.OtcFishingCrabTrab.bone.group4] run function otc_crab_trap:model/animations/crab.move/tree/group4_display_top
execute if entity @s[tag=aj.OtcFishingCrabTrab.bone.group5] run function otc_crab_trap:model/animations/crab.move/tree/group5_display_top
execute if entity @s[tag=aj.OtcFishingCrabTrab.bone.bone] run function otc_crab_trap:model/animations/crab.move/tree/bone_display_top
execute if entity @s[tag=aj.OtcFishingCrabTrab.bone.group] run function otc_crab_trap:model/animations/crab.move/tree/group_display_top
execute if entity @s[tag=aj.OtcFishingCrabTrab.bone.crab_export3] run function otc_crab_trap:model/animations/crab.move/tree/crab_export3_display_top
execute if entity @s[tag=aj.OtcFishingCrabTrab.bone.crab_export4] run function otc_crab_trap:model/animations/crab.move/tree/crab_export4_display_top
execute if entity @s[tag=aj.OtcFishingCrabTrab.bone.crab_export5] run function otc_crab_trap:model/animations/crab.move/tree/crab_export5_display_top
execute if entity @s[tag=aj.OtcFishingCrabTrab.bone.crab_export] run function otc_crab_trap:model/animations/crab.move/tree/crab_export_display_top
execute if entity @s[tag=aj.OtcFishingCrabTrab.bone.crab_export2] run function otc_crab_trap:model/animations/crab.move/tree/crab_export2_display_top
execute positioned as @s run tp @s ~ ~ ~ ~ ~