#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.OtcFishingCrabTrab.bone.group2] run function otc_crab_trap:model/animations/crab.move/tree/group2_root_top
execute if entity @s[tag=aj.OtcFishingCrabTrab.bone.group3] run function otc_crab_trap:model/animations/crab.move/tree/group3_root_top
execute if entity @s[tag=aj.OtcFishingCrabTrab.bone.group4] run function otc_crab_trap:model/animations/crab.move/tree/group4_root_top
execute if entity @s[tag=aj.OtcFishingCrabTrab.bone.group5] run function otc_crab_trap:model/animations/crab.move/tree/group5_root_top
execute if entity @s[tag=aj.OtcFishingCrabTrab.bone.bone] run function otc_crab_trap:model/animations/crab.move/tree/bone_root_top
execute if entity @s[tag=aj.OtcFishingCrabTrab.bone.group] run function otc_crab_trap:model/animations/crab.move/tree/group_root_top
execute if entity @s[tag=aj.OtcFishingCrabTrab.bone.crab_export3] run function otc_crab_trap:model/animations/crab.move/tree/crab_export3_root_top
execute if entity @s[tag=aj.OtcFishingCrabTrab.bone.crab_export4] run function otc_crab_trap:model/animations/crab.move/tree/crab_export4_root_top
execute if entity @s[tag=aj.OtcFishingCrabTrab.bone.crab_export5] run function otc_crab_trap:model/animations/crab.move/tree/crab_export5_root_top
execute if entity @s[tag=aj.OtcFishingCrabTrab.bone.crab_export] run function otc_crab_trap:model/animations/crab.move/tree/crab_export_root_top
execute if entity @s[tag=aj.OtcFishingCrabTrab.bone.crab_export2] run function otc_crab_trap:model/animations/crab.move/tree/crab_export2_root_top
execute store result entity @s Air short 1 run scoreboard players get .this aj.frame