#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.OtcFishingCrabTrab.crab.move.loopMode matches 0 run function otc_crab_trap:model/animations/crab.move/stop
execute if score @s aj.OtcFishingCrabTrab.crab.move.loopMode matches 1 run function otc_crab_trap:model/animations/crab.move/pause
execute if score @s aj.OtcFishingCrabTrab.crab.move.loopMode matches 2 run function otc_crab_trap:model/animations/crab.move/zzz/execute/19