#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.OtcFishingCrabTrab.root] at @s run function otc_crab_trap:model/animations/crab.move/zzz/conditional/10
execute if score #execute aj.i matches 0 run function otc_crab_trap:model/animations/crab.move/zzz/conditional/11