#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.OtcFishingCrabTrab.anim.crab.move
execute if score .aj.anim_loop aj.OtcFishingCrabTrab.animating matches 0 run function otc_crab_trap:model/animation_loop
scoreboard players set #execute aj.i 1