#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.crab_trap.bone.group2] run function crab_trap:animations/crab.empty/tree/group2_display_top
execute if entity @s[tag=aj.crab_trap.bone.group3] run function crab_trap:animations/crab.empty/tree/group3_display_top
execute if entity @s[tag=aj.crab_trap.bone.group4] run function crab_trap:animations/crab.empty/tree/group4_display_top
execute if entity @s[tag=aj.crab_trap.bone.group5] run function crab_trap:animations/crab.empty/tree/group5_display_top
execute if entity @s[tag=aj.crab_trap.bone.bone] run function crab_trap:animations/crab.empty/tree/bone_display_top
execute if entity @s[tag=aj.crab_trap.bone.group] run function crab_trap:animations/crab.empty/tree/group_display_top
execute if entity @s[tag=aj.crab_trap.bone.crab_export3] run function crab_trap:animations/crab.empty/tree/crab_export3_display_top
execute if entity @s[tag=aj.crab_trap.bone.crab_export4] run function crab_trap:animations/crab.empty/tree/crab_export4_display_top
execute if entity @s[tag=aj.crab_trap.bone.crab_export5] run function crab_trap:animations/crab.empty/tree/crab_export5_display_top
execute if entity @s[tag=aj.crab_trap.bone.crab_export] run function crab_trap:animations/crab.empty/tree/crab_export_display_top
execute if entity @s[tag=aj.crab_trap.bone.crab_export2] run function crab_trap:animations/crab.empty/tree/crab_export2_display_top
execute positioned as @s run tp @s ~ ~ ~ ~ ~