#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set # aj.i 1
execute at @s as @e[type=#crab_trap:bone_entities,tag=aj.crab_trapCrabTrap.bone] if score @s aj.id = .this aj.id run function crab_trap:zzz/execute/14