#Project generated by Animated Java (https://animated-java.dev/)

tp @s[tag=aj.crab_trap.bone.group2] ^0 ^-1.813 ^-0.047
tp @s[tag=aj.crab_trap.bone.group3] ^0 ^-1.813 ^-0.75
tp @s[tag=aj.crab_trap.bone.group4] ^-0.75 ^-1.45 ^-0.375
tp @s[tag=aj.crab_trap.bone.group5] ^0 ^-1.813 ^0
tp @s[tag=aj.crab_trap.bone.group] ^0 ^-1.813 ^0
tp @s[tag=aj.crab_trap.bone.crab_export2] ^0.016 ^-1.594 ^-0.318
tp @s[tag=aj.crab_trap.bone.crab_export3] ^0.168 ^-1.719 ^-0.081
tp @s[tag=aj.crab_trap.bone.crab_export4] ^-0.307 ^-1.467 ^0.122
tp @s[tag=aj.crab_trap.bone.crab_export5] ^-0.089 ^-1.717 ^0.122
tp @s[tag=aj.crab_trap.bone.crab_export] ^0.327 ^-1.28 ^0.106
tp @s[tag=aj.crab_trap.bone.bone] ^0 ^-1.813 ^0
execute store result score .calc aj.i run data get entity @s Air
execute store result entity @s Air short 1 run scoreboard players add .calc aj.i 2