#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.crab_trap.bone.group2] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.crab_trap.bone.group3] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.crab_trap.bone.group4] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.crab_trap.bone.group5] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.crab_trap.bone.group] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.crab_trap.bone.crab_export2] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.crab_trap.bone.crab_export3] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.crab_trap.bone.crab_export4] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.crab_trap.bone.crab_export5] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.crab_trap.bone.crab_export] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.crab_trap.bone.bone] Pose.Head set value [0f,0f,0f]
tp @s ~ ~ ~ ~ ~