#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.OtcFishingCrabTrab.crab.empty.loopMode matches 0 run function otc_crab_trap:model/animations/crab.empty/stop
execute if score @s aj.OtcFishingCrabTrab.crab.empty.loopMode matches 1 run function otc_crab_trap:model/animations/crab.empty/pause
execute if score @s aj.OtcFishingCrabTrab.crab.empty.loopMode matches 2 run function otc_crab_trap:model/animations/crab.empty/zzz/execute/20