#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.crab_trap.crab.empty.loopMode matches 0 run function crab_trap:animations/crab.empty/stop
execute if score @s aj.crab_trap.crab.empty.loopMode matches 1 run function crab_trap:animations/crab.empty/pause
execute if score @s aj.crab_trap.crab.empty.loopMode matches 2 run function crab_trap:animations/crab.empty/zzz/execute/20