#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.crab_trap.root] run function crab_trap:animations/crab.empty/zzz/conditional/22
execute if score #execute aj.i matches 0 run function crab_trap:animations/crab.empty/zzz/conditional/23